export enum Colors {
    LIGHT_GREY = 'light grey',
    GREY = 'grey',
    LIGHT_ORANGE = 'light orange',
    ORANGE = 'orange',
    DARK_ORANGE = 'dark orange',
    GREEN = 'green',
    BLUE = 'blue',
    PINK = 'pink',
    DARK_GREEN = 'dark green',
    RED = 'red',
    DARK_GREY = 'dark grey',
    CLAY_RED = 'brown',
    LIGHT_BLUE = 'light blue',
    DARK_PURPLE = 'dark purple',
    BLACK = 'black',
}
